version: "3"

services:
  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

  mysql:
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=yii2advanced
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 1500:80
    restart: always
    environment:
      - PMA_HOST=mysql

