networks:
  yii:
    name: yii

services:
  yii-frontend:
    container_name: yii_frontend
    build: ./frontend
    volumes:
      - ./frontend:/var/www/frontend
    networks:
      - yii
    depends_on:
      - mysql

  yii-backend:
    container_name: yii_backend
    build: ./backend
    volumes:
      - ./backend:/var/www/backend
    networks:
      - yii
    depends_on:
      - mysql

  nginx:
    container_name: yii_nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yii
    depends_on:
      - yii-frontend
      - yii-backend

  mysql:
    container_name: yii_mysql
    image: mysql:latest
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_USER=yii
      - MYSQL_PASSWORD=yii
      - MYSQL_ROOT_PASSWORD=yii
      - MYSQL_DATABASE=yii
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - yii